#!/usr/bin/env bash
# Generate the k8s objects for one more browser profile.
#
# Each profile is an independent browser identity: its own Chrome profile on
# its own PVC, its own Deployment, its own Service. They are never scaled past
# one replica, because a Chrome profile directory is single-writer.
#
#   ./scripts/add-profile.sh linkedin >> k8s/profiles/linkedin.yaml
#
# Then apply it and log in once over noVNC (see docs/OPERATING.md).
set -euo pipefail

NAME="${1:-}"
if [ -z "$NAME" ]; then
  echo "usage: $0 <profile-name>   e.g. $0 linkedin" >&2
  exit 1
fi
if ! printf '%s' "$NAME" | grep -qE '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
  echo "error: profile name must be lowercase alphanumeric with dashes" >&2
  exit 1
fi

IMAGE="${IMAGE:-localhost:5000/browser-agent:latest}"
STORAGE="${STORAGE:-2Gi}"
SCREEN="${SCREEN:-1440x900}"
WIDTH="${SCREEN%x*}"
HEIGHT="${SCREEN#*x}"

cat <<YAML
# Generated by scripts/add-profile.sh $NAME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-$NAME
  namespace: browser-agent
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: $STORAGE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-$NAME
  namespace: browser-agent
  labels: { app: browser-agent, profile: $NAME }
spec:
  # A browser profile is single-writer: never two pods against one PVC.
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: { app: browser-agent, profile: $NAME }
  template:
    metadata:
      labels: { app: browser-agent, profile: $NAME }
    spec:
      # Reaps Chrome's helper processes; the k8s equivalent of tini.
      shareProcessNamespace: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      # cn1 is amd64, office-server is arm64. The image ships as a single amd64
      # manifest, so an unpinned pod scheduled onto office-server dies with an
      # exec-format error. Build multi-arch before removing this.
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: agent
          image: $IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - { name: api, containerPort: 8000 }
            - { name: novnc, containerPort: 6080 }
          env:
            - { name: AGENT_PROFILE, value: $NAME }
            - { name: PROFILES_ROOT, value: /profiles }
            - { name: DATA_ROOT, value: /data }
            - { name: NOVNC_PORT, value: "6080" }
            - { name: SCREEN_WIDTH, value: "$WIDTH" }
            - { name: SCREEN_HEIGHT, value: "$HEIGHT" }
            - { name: LLM_BASE_URL, value: "http://llm-service.llm-service.svc.cluster.local:8001/v1" }
            - { name: LLM_MODEL, value: "glm-4.5v" }
            - { name: LLM_ENABLED, value: "true" }
            # Residential egress. A datacenter IP is the fastest way to get a
            # session flagged, so this is not optional. Named BROWSER_PROXY,
            # not HTTP_PROXY: the conventional names are honoured implicitly by
            # every HTTP client in the process, which would route the
            # in-cluster LLM call through the proxy and fail.
            - { name: BROWSER_PROXY, value: "socks5://office-proxy.crawl.svc.cluster.local:1080" }
          envFrom:
            - secretRef: { name: browser-agent-secrets }
          resources:
            requests: { cpu: 500m, memory: 1Gi }
            limits: { cpu: "2", memory: 3Gi }
          volumeMounts:
            - { name: profile, mountPath: /profiles }
            - { name: data, mountPath: /data }
          readinessProbe:
            httpGet: { path: /healthz, port: api }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: api }
            initialDelaySeconds: 20
            periodSeconds: 30
      volumes:
        - name: profile
          persistentVolumeClaim: { claimName: profile-$NAME }
        - name: data
          emptyDir: { sizeLimit: 256Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: profile-$NAME
  namespace: browser-agent
  labels: { app: browser-agent, profile: $NAME }
spec:
  type: ClusterIP
  selector: { app: browser-agent, profile: $NAME }
  ports:
    - { name: api, port: 8000, targetPort: api }
    - { name: novnc, port: 6080, targetPort: novnc }
YAML
