#!/usr/bin/env bash
# Generate the k8s objects for one more browser profile — a "bot".
#
# Each profile is an independent browser identity: its own Chrome profile on
# its own PVC, its own Deployment, its own Service, its own admin UI and its
# own live view. They are never scaled past one replica, because a Chrome
# profile directory is single-writer.
#
#   ./scripts/add-profile.sh linkedin > k8s/profiles/linkedin.yaml
#   kubectl apply -f k8s/profiles/linkedin.yaml
#
# Then log in once over noVNC (see docs/OPERATING.md) and expose it with
# k8s/local/deploy.sh, which is what fills in BROWSER_BASE_URL.
#
# Every env below is copied from k8s/browser-agent.yaml on purpose: a new
# profile has to come up with the same model, picker and bounds as profile-x,
# or it is born broken. Keep the two files in step when either changes.
set -euo pipefail

NAME="${1:-}"
if [ -z "$NAME" ]; then
  echo "usage: $0 <profile-name>   e.g. $0 linkedin" >&2
  exit 1
fi
if ! printf '%s' "$NAME" | grep -qE '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
  echo "error: profile name must be lowercase alphanumeric with dashes" >&2
  exit 1
fi

IMAGE="${IMAGE:-localhost:5000/browser-agent:latest}"
STORAGE="${STORAGE:-2Gi}"
SCREEN="${SCREEN:-1440x900}"
WIDTH="${SCREEN%x*}"
HEIGHT="${SCREEN#*x}"
# What the roster will call this bot. Both are quoted for YAML, because the
# operator writes a sentence here and a bare colon or # would parse as YAML.
BOT_NAME="$(printf '%s' "${BOT_NAME:-}" | tr -d '\n\r\\"' | tr -s ' ')"
BOT_JOB="$(printf '%s' "${BOT_JOB:-}" | tr -d '\n\r\\"' | tr -s ' ')"

cat <<YAML
# Generated by scripts/add-profile.sh $NAME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-$NAME
  namespace: browser-agent
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: $STORAGE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-$NAME
  namespace: browser-agent
  labels: { app: browser-agent, profile: $NAME }
spec:
  # A browser profile is single-writer: never two pods against one PVC.
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: { app: browser-agent, profile: $NAME }
  template:
    metadata:
      labels: { app: browser-agent, profile: $NAME }
    spec:
      # A fixed hostname, because it leaks into Chrome's profile lock.
      # user_data_dir/SingletonLock is a symlink whose target text is
      # "<hostname>-<pid>", and a pod's default hostname is its own name —
      # which changes on every recreate while the profile sits on a stable
      # PVC. If Chrome is killed rather than closed, the stale lock names a
      # host that no longer exists and Chrome exits PROFILE_IN_USE. Pinning
      # the same constant every profile uses keeps the lock valid.
      hostname: browser-agent
      # Reaps Chrome's helper processes; the k8s equivalent of tini.
      shareProcessNamespace: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      # cn1 is amd64, office-server is arm64. The image ships as a single amd64
      # manifest, so an unpinned pod scheduled onto office-server dies with an
      # exec-format error. Build multi-arch before removing this.
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: agent
          image: $IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - { name: api, containerPort: 8000 }
            - { name: novnc, containerPort: 6080 }
          env:
            - { name: AGENT_PROFILE, value: $NAME }
            - { name: PROFILES_ROOT, value: /profiles }
            - { name: DATA_ROOT, value: /data }
            - { name: NOVNC_PORT, value: "6080" }
            # Deployment-specific and kept local, exactly as in the tracked
            # manifest: k8s/local/deploy.sh sets it to the real host. Empty is
            # safe — the UI falls back to its own origin for the live view.
            - { name: BROWSER_BASE_URL, value: "" }
            - { name: SCREEN_WIDTH, value: "$WIDTH" }
            - { name: SCREEN_HEIGHT, value: "$HEIGHT" }
            - { name: AGENT_MAX_STEPS, value: "25" }
            - { name: AGENT_TIMEOUT_S, value: "600" }
            # LLM fallback: llm-service, in-cluster. No per-call fees.
            - { name: LLM_BASE_URL, value: "http://llm-service.llm-service.svc.cluster.local:8001/v1" }
            # deepseek-v4.1-flash, not glm-4.5v. The vision GLM is zai-ONLY in
            # llm-service (no twin in Ollama Cloud), so it has no failover and
            # a wedged zai hangs every escalation for the full budget. This id
            # is on ollama_cloud, answers in <1s and handles image parts.
            - { name: LLM_MODEL, value: "deepseek-v4.1-flash" }
            - { name: LLM_ENABLED, value: "true" }
            - { name: LLM_SOURCE, value: "browser-agent" }
            - { name: LLM_CLIENT_ID, value: "browser-agent" }
            - { name: PLANNER_MODEL, value: "deepseek-v4.1-flash" }
            - { name: PLANNER_MAX_STEPS, value: "12" }
            - { name: PLANNER_STEP_TIMEOUT_S, value: "10" }
            - { name: PLANNER_CLIENT_ID, value: "browser-agent-planner" }
            # Laya keeps CONFIRM only. PICK is off on coverage, not accuracy:
            # re-benched in-pod 2026-09-22 against prod /v1/decide — 14/18
            # correct (78%) with 100% precision on everything that cleared the
            # 0.75 floor, but only 22% cleared it (bench bar is 80%). It would
            # not misclick; it would just abstain on ~4 of 5 decisions.
            # CONFIRM's failure mode is a repair attempt.
            - { name: LAYA_ENABLED, value: "true" }
            - { name: LAYA_DECIDE_URL, value: "http://llm-service.llm-service.svc.cluster.local:8001/v1/decide" }
            - { name: LAYA_PICK_ENABLED, value: "false" }
            # The minesweeper tiebreak gates on LAYA_ENABLED, not PICK_ENABLED,
            # so the game leans on Laya while the plan picker stays off.
            # Measured in-pod 2026-09-22 (scripts/laya_game_bench.py): solver
            # top pick safe 17/17, Laya 16/17, agreement 0/17 — Laya is the
            # weaker guesser, so this floor, not taste, is what keeps it safe.
            - { name: LAYA_GAME_MIN_CONFIDENCE, value: "0.55" }
            - { name: LAYA_MIN_CONFIDENCE, value: "0.75" }
            # 10 = the calibrated choice range (buckets >=11 ship distorted
            # temperatures) and fits the 512-token budget.
            - { name: LAYA_MAX_CANDIDATES, value: "10" }
            - { name: LAYA_PICK_RETRIES, value: "1" }
            # Element picker: same numbered-lines/bind-by-index contract as
            # laya's, but the model is deepseek-v4.1-flash — benched 18/18 at
            # ~1 s/pick where laya scored 4/18.
            - { name: PICKER_ENABLED, value: "true" }
            - { name: PICKER_MODEL, value: "deepseek-v4.1-flash" }
            - { name: PICKER_CLIENT_ID, value: "browser-agent-picker" }
            # What the roster shows for this bot. Set by the hub from what the
            # operator typed; empty when a profile is generated by hand, and
            # the roster falls back to the profile name.
            - { name: BOT_NAME, value: "$BOT_NAME" }
            - { name: BOT_JOB, value: "$BOT_JOB" }
            # The path the roster proxies this bot at. Only ever cosmetic: it
            # decides the live-view URL the bot advertises, never its routing.
            - { name: BROWSER_URL_PREFIX, value: "/b/$NAME" }
            # Residential egress. A datacenter IP is the fastest way to get a
            # session flagged, so this is not optional. Named BROWSER_PROXY,
            # not HTTP_PROXY: the conventional names are honoured implicitly by
            # every HTTP client in the process, which would route the
            # in-cluster LLM call through the proxy and fail.
            - { name: BROWSER_PROXY, value: "socks5://office-proxy.crawl.svc.cluster.local:1080" }
          envFrom:
            - secretRef: { name: browser-agent-secrets }
          resources:
            requests: { cpu: 500m, memory: 1Gi }
            limits: { cpu: "2", memory: 3Gi }
          volumeMounts:
            - { name: profile, mountPath: /profiles }
            - { name: data, mountPath: /data }
          readinessProbe:
            httpGet: { path: /healthz, port: api }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: api }
            initialDelaySeconds: 20
            periodSeconds: 30
      volumes:
        - name: profile
          persistentVolumeClaim: { claimName: profile-$NAME }
        - name: data
          emptyDir: { sizeLimit: 256Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: profile-$NAME
  namespace: browser-agent
  labels: { app: browser-agent, profile: $NAME }
spec:
  type: ClusterIP
  selector: { app: browser-agent, profile: $NAME }
  ports:
    - { name: api, port: 8000, targetPort: api }
    - { name: novnc, port: 6080, targetPort: novnc }
YAML
