#!/usr/bin/env bash
# Bring up N local profile containers at once (docker compose).
#
#   ./scripts/profiles-up.sh x linkedin facebook
#
# Writes a docker-compose override with one service per profile and starts it.
# Each profile gets its own Chrome profile directory and its own ports:
#   admin UI  8900 + index
#   noVNC     6080 + index
#
# This is the local equivalent of one Deployment per profile in k8s.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ "$#" -eq 0 ]; then
  echo "usage: $0 <profile> [profile...]" >&2
  exit 1
fi

OVERRIDE="docker-compose.profiles.yaml"
IMAGE="${IMAGE:-browser-agent:local}"
: > "$OVERRIDE"

{
  echo "# Generated by scripts/profiles-up.sh — one service per browser profile."
  echo "services:"
} >> "$OVERRIDE"

i=0
for name in "$@"; do
  if ! printf '%s' "$name" | grep -qE '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
    echo "error: bad profile name: $name" >&2
    exit 1
  fi
  ui=$((8900 + i))
  vnc=$((6080 + i))
  mkdir -p "profiles/$name" "data/$name"

  cat >> "$OVERRIDE" <<YAML
  profile-$name:
    build: .
    image: $IMAGE
    restart: unless-stopped
    shm_size: 2g
    init: true
    user: "\${UID:-1000}:\${GID:-1000}"
    container_name: browser-agent-$name
    environment:
      AGENT_PROFILE: $name
      PROFILES_ROOT: /profiles
      DATA_ROOT: /data
      NOVNC_PORT: "6080"
      CONTROL_TOKEN: \${CONTROL_TOKEN:-devtoken}
      LLM_ENABLED: \${LLM_ENABLED:-false}
      LLM_BASE_URL: \${LLM_BASE_URL:-}
      LLM_MODEL: \${LLM_MODEL:-glm-4.5v}
      NOTIFY_ON_ESCALATION: "false"
    ports:
      - "127.0.0.1:$ui:8000"
      - "127.0.0.1:$vnc:6080"
    volumes:
      - ./profiles/$name:/profiles/$name
      - ./data/$name:/data
YAML

  echo "  profile-$name -> admin :$ui  noVNC :$vnc"
  i=$((i + 1))
done

echo
echo "wrote $OVERRIDE; starting..."
CONTROL_TOKEN="${CONTROL_TOKEN:-devtoken}" \
  docker compose -f docker-compose.yaml -f "$OVERRIDE" up -d --build
