"""The roster: one page that lists every bot, and opens each one's own window.

This is a *separate process* from a bot on purpose. A bot is one identity with
one browser, and the whole security model rests on that being isolated; a
roster that also drove a browser would blur it. The hub owns no Chrome, no
profile and no task queue — it reads the registry, asks each bot pod who it is,
and renders links.

That is also why every bot link is a plain URL to the bot's own pod rather than
a proxy through here: the roster must not become a deputy that can reach every
logged-in account through one credential. nginx strips /b/<profile> and proxies
straight to the pod, so the browser talks to the bot directly and the hub is
never in the data path.

Adding a bot is the one privileged action: it has to create a PVC, a Deployment
and a Service. The manifest is generated by scripts/add-profile.sh, so there is
exactly one definition of what a bot is; this module only runs it and applies
the result.
"""

from __future__ import annotations

import asyncio
import logging
import subprocess
from pathlib import Path
from typing import Any

import httpx
from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

from . import registry
from .config import load_settings

log = logging.getLogger("browser_agent.hub")

settings = load_settings()
app = FastAPI(title="browser-agent roster")


# -- auth ------------------------------------------------------------------


async def require_token(request: Request) -> None:
    if not settings.control_token:
        return
    header = request.headers.get("authorization", "")
    if header.removeprefix("Bearer ").strip() != settings.control_token:
        raise HTTPException(status_code=401, detail="unauthorized")


# -- talking to the bots ---------------------------------------------------


async def _probe(client: httpx.AsyncClient, bot: registry.Bot) -> dict[str, Any]:
    """Ask one bot pod who it is. Never raises: a bot that is down is a state
    the roster renders, not an error that breaks the page."""
    url = f"http://profile-{bot.profile}:{settings.api_port}/api/whoami"
    headers = {"Authorization": f"Bearer {settings.control_token}"}
    try:
        res = await client.get(url, headers=headers)
        if res.status_code != 200:
            return {"reachable": False, "error": f"http {res.status_code}"}
        return {"reachable": True, **res.json()}
    except httpx.HTTPError as exc:
        return {"reachable": False, "error": type(exc).__name__}


@app.get("/healthz")
async def healthz() -> dict[str, Any]:
    reg = registry.load(settings.registry_path)
    return {"ok": True, "profile": settings.profile, "bots": len(reg.bots)}


@app.get("/api/bots", dependencies=[Depends(require_token)])
async def list_bots() -> dict[str, Any]:
    """The roster, with each bot's live state merged in.

    The registry is authoritative for naming (what the operator called it); the
    pod is authoritative for whether it is up and signed in. Where they
    disagree — a bot on the roster with no pod yet, or a pod created by hand
    that nobody registered — the roster shows both rather than picking one, so
    the disagreement is visible instead of silently resolved.
    """
    reg = registry.load(settings.registry_path)

    async with httpx.AsyncClient(timeout=settings.bot_probe_timeout_s, trust_env=False) as client:
        probes = await asyncio.gather(*(_probe(client, b) for b in reg.bots))

    bots = []
    for bot, probe in zip(reg.bots, probes, strict=True):
        bots.append({
            **bot.to_dict(),
            "profile": bot.profile,
            "reachable": probe.get("reachable", False),
            "error": probe.get("error", ""),
            # The pod's own answer wins on whether a human has signed in: it is
            # read off the PVC, whereas the registry only knows what it was told.
            "signed_in": bool(probe.get("reachable") and probe.get("profile_initialised")),
        })

    return {
        "bots": bots,
        "url_prefix": settings.url_prefix,
        "can_create": _can_create(),
    }


def _can_create() -> bool:
    """Whether this hub is allowed to add a bot. False when the script or the
    cluster client is missing, which is the honest answer rather than a button
    that fails after the click."""
    return (
        Path(settings.add_profile_script).is_file()
        and _which(settings.kubectl_bin) is not None
    )


def _which(binary: str) -> str | None:
    from shutil import which

    return which(binary)


# -- models ----------------------------------------------------------------


class CreateBot(BaseModel):
    profile: str
    name: str = ""
    job: str = ""
    notes: str = ""


class PatchBot(BaseModel):
    name: str | None = None
    job: str | None = None
    notes: str | None = None
    hidden: bool | None = None


@app.post("/api/bots", dependencies=[Depends(require_token)])
async def create_bot(req: CreateBot) -> dict[str, Any]:
    """Add a bot: register it, generate its manifest, apply it.

    Order matters. The manifest is generated and applied BEFORE the registry is
    written, because a registry entry with no pod is a roster line that will
    never come up — whereas a pod with no registry entry is just a bot that
    shows as unreachable until it is named, and repairing that is one edit.
    """
    if not registry.valid_profile(req.profile):
        raise HTTPException(400, "profile must be lowercase letters, digits and dashes")
    if registry.load(settings.registry_path).get(req.profile):
        raise HTTPException(409, f"a bot named {req.profile} is already on the roster")
    if not _can_create():
        raise HTTPException(
            503, "this hub cannot create bots: add-profile.sh or kubectl is missing"
        )

    manifest = settings.registry_path.parent / f"profile-{req.profile}.yaml"
    try:
        out = subprocess.run(
            [settings.add_profile_script, req.profile],
            capture_output=True, text=True, timeout=30, check=True,
        )
        manifest.write_text(out.stdout)
        applied = subprocess.run(
            [settings.kubectl_bin, "-n", settings.namespace, "apply", "-f", str(manifest)],
            capture_output=True, text=True, timeout=60,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise HTTPException(500, f"could not create the bot: {exc}") from exc

    if applied.returncode != 0:
        raise HTTPException(500, f"kubectl apply failed: {applied.stderr.strip()[:400]}")

    reg = registry.load(settings.registry_path)
    bot = registry.upsert(reg, req.profile, name=req.name, job=req.job,
                          notes=req.notes, url=f"/b/{req.profile}/")
    registry.save(settings.registry_path, reg)
    log.info("created bot %s", req.profile)
    return {"ok": True, "bot": bot.to_dict(), "kubectl": applied.stdout.strip()[:400]}


@app.patch("/api/bots/{profile}", dependencies=[Depends(require_token)])
async def patch_bot(profile: str, req: PatchBot) -> dict[str, Any]:
    reg = registry.load(settings.registry_path)
    if reg.get(profile) is None:
        raise HTTPException(404, f"no bot named {profile}")
    bot = registry.upsert(reg, profile, **req.model_dump(exclude_none=True))
    registry.save(settings.registry_path, reg)
    return {"ok": True, "bot": bot.to_dict()}


@app.get("/", response_class=HTMLResponse)
async def roster_page() -> HTMLResponse:
    ui = Path(__file__).parent / "ui" / "roster.html"
    return HTMLResponse(ui.read_text())
