"""The roster: one page that lists every bot, and opens each one's own window.

This is a *separate process* from a bot on purpose. A bot is one identity with
one browser, and the whole security model rests on that being isolated; a
roster that also drove a browser would blur it. The hub owns no Chrome, no
profile and no task queue — it reads the registry, asks each bot pod who it is,
and renders links.

That is also why every bot link is a plain URL to the bot's own pod rather than
a proxy through here: the roster must not become a deputy that can reach every
logged-in account through one credential. nginx strips /b/<profile> and proxies
straight to the pod, so the browser talks to the bot directly and the hub is
never in the data path.

Adding a bot is the one privileged action: it has to create a PVC, a Deployment
and a Service. The manifest is generated by scripts/add-profile.sh, so there is
exactly one definition of what a bot is; this module only runs it and applies
the result.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
import os
import subprocess
import time
from pathlib import Path
from typing import Any

import httpx
from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

from . import farms, recipe_store, registry
from .config import load_settings
from .plan_model import PlanRejected

log = logging.getLogger("browser_agent.hub")

settings = load_settings()

# The farm store lives beside the roster on the hub's volume, so an assignment
# survives a hub restart: a farm scheduled for 10:00 must still fire at 10:00
# even if the pod was recreated at 09:58. The runner is started by the app
# lifespan, so the loop only exists while the process is actually serving.
farm_store = farms.FarmStore(settings.registry_path.parent / "farms.json")
farm_runner = farms.FarmRunner(farm_store, settings)


@contextlib.asynccontextmanager
async def _lifespan(app: FastAPI) -> Any:
    farm_runner.start()
    yield
    await farm_runner.stop()


app = FastAPI(title="browser-agent roster", lifespan=_lifespan)


# -- auth ------------------------------------------------------------------


async def require_token(request: Request) -> None:
    if not settings.control_token:
        return
    header = request.headers.get("authorization", "")
    if header.removeprefix("Bearer ").strip() != settings.control_token:
        raise HTTPException(status_code=401, detail="unauthorized")


# -- talking to the bots ---------------------------------------------------


async def _probe(client: httpx.AsyncClient, bot: registry.Bot) -> dict[str, Any]:
    """Ask one bot pod who it is. Never raises: a bot that is down is a state
    the roster renders, not an error that breaks the page."""
    url = settings.bot_url_template.format(
        profile=bot.profile, api_port=settings.api_port
    ) + "/api/whoami"
    headers = {"Authorization": f"Bearer {settings.control_token}"}
    try:
        res = await client.get(url, headers=headers)
        if res.status_code != 200:
            return {"reachable": False, "error": f"http {res.status_code}"}
        return {"reachable": True, **res.json()}
    except httpx.HTTPError as exc:
        return {"reachable": False, "error": type(exc).__name__}


@app.get("/healthz")
async def healthz() -> dict[str, Any]:
    reg = registry.load(settings.registry_path)
    return {"ok": True, "profile": settings.profile, "bots": len(reg.bots)}


@app.get("/api/bots", dependencies=[Depends(require_token)])
async def list_bots() -> dict[str, Any]:
    """The roster, with each bot's live state merged in.

    The registry is authoritative for naming (what the operator called it); the
    pod is authoritative for whether it is up and signed in. Where they
    disagree — a bot on the roster with no pod yet, or a pod created by hand
    that nobody registered — the roster shows both rather than picking one, so
    the disagreement is visible instead of silently resolved.
    """
    reg = registry.load(settings.registry_path)

    async with httpx.AsyncClient(timeout=settings.bot_probe_timeout_s, trust_env=False) as client:
        probes = await asyncio.gather(*(_probe(client, b) for b in reg.bots))

    bots = []
    for bot, probe in zip(reg.bots, probes, strict=True):
        bots.append({
            **bot.to_dict(),
            "profile": bot.profile,
            "reachable": probe.get("reachable", False),
            "error": probe.get("error", ""),
            # The pod's own answer wins on whether a human has signed in: it is
            # read off the PVC, whereas the registry only knows what it was told.
            "signed_in": bool(probe.get("reachable") and probe.get("profile_initialised")),
            # Which identity is live, and how many the bot holds. Roster-level
            # only: the per-account detail lives on the bot's own page, because
            # polling four cookie counts for every bot on every roster refresh
            # is work the roster has no use for.
            "account": probe.get("account", ""),
            "account_label": probe.get("account_label", ""),
            "accounts": probe.get("accounts", 0),
        })

    return {
        "bots": bots,
        "url_prefix": settings.url_prefix,
        "can_create": _can_create(),
    }


def _can_create() -> bool:
    """Whether this hub is allowed to add a bot. False when the script or the
    cluster client is missing, which is the honest answer rather than a button
    that fails after the click."""
    return (
        Path(settings.add_profile_script).is_file()
        and _which(settings.kubectl_bin) is not None
    )


def _which(binary: str) -> str | None:
    from shutil import which

    return which(binary)


# -- models ----------------------------------------------------------------


class CreateBot(BaseModel):
    profile: str
    name: str = ""
    job: str = ""
    notes: str = ""


class PatchBot(BaseModel):
    name: str | None = None
    job: str | None = None
    notes: str | None = None
    background: str | None = None
    login_notes: str | None = None
    hidden: bool | None = None


class RecipeSpec(BaseModel):
    """One operator-authored recipe: a saved plan plus an identity."""

    name: str
    description: str = ""
    entry_url: str
    steps: list[dict[str, Any]] = []


class ConfigPatch(BaseModel):
    """Overrides for one built-in recipe, keyed by the names in OVERRIDABLE."""

    values: dict[str, Any] = {}


@app.post("/api/bots", dependencies=[Depends(require_token)])
async def create_bot(req: CreateBot) -> dict[str, Any]:
    """Add a bot: register it, generate its manifest, apply it.

    Order matters. The manifest is generated and applied BEFORE the registry is
    written, because a registry entry with no pod is a roster line that will
    never come up — whereas a pod with no registry entry is just a bot that
    shows as unreachable until it is named, and repairing that is one edit.
    """
    if not registry.valid_profile(req.profile):
        raise HTTPException(400, "profile must be lowercase letters, digits and dashes")
    if registry.load(settings.registry_path).get(req.profile):
        raise HTTPException(409, f"a bot named {req.profile} is already on the roster")
    if not _can_create():
        raise HTTPException(
            503, "this hub cannot create bots: add-profile.sh or kubectl is missing"
        )

    manifest = settings.registry_path.parent / f"profile-{req.profile}.yaml"
    # BOT_NAME/BOT_JOB are what the *pod* renders as its own title — add-profile.sh
    # reads them and writes them into the Deployment env. Without them the pod
    # only knows its profile slug, so a bot the operator named "LinkedIn outreach"
    # shows up inside its own window as "linkedin". Passing them here is what
    # makes the roster's name and the bot's own name the same name.
    env = {**os.environ, "BOT_NAME": req.name or "", "BOT_JOB": req.job or ""}
    try:
        out = subprocess.run(
            [settings.add_profile_script, req.profile],
            capture_output=True, text=True, timeout=30, check=True, env=env,
        )
        manifest.write_text(out.stdout)
        applied = subprocess.run(
            [settings.kubectl_bin, "-n", settings.namespace, "apply", "-f", str(manifest)],
            capture_output=True, text=True, timeout=60,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise HTTPException(500, f"could not create the bot: {exc}") from exc

    if applied.returncode != 0:
        raise HTTPException(500, f"kubectl apply failed: {applied.stderr.strip()[:400]}")

    reg = registry.load(settings.registry_path)
    bot = registry.upsert(reg, req.profile, name=req.name, job=req.job,
                          notes=req.notes, url=f"/b/{req.profile}/")
    registry.save(settings.registry_path, reg)
    log.info("created bot %s", req.profile)
    return {"ok": True, "bot": bot.to_dict(), "kubectl": applied.stdout.strip()[:400]}


@app.patch("/api/bots/{profile}", dependencies=[Depends(require_token)])
async def patch_bot(profile: str, req: PatchBot) -> dict[str, Any]:
    reg = registry.load(settings.registry_path)
    if reg.get(profile) is None:
        raise HTTPException(404, f"no bot named {profile}")
    bot = registry.upsert(reg, profile, **req.model_dump(exclude_none=True))
    registry.save(settings.registry_path, reg)
    return {"ok": True, "bot": bot.to_dict()}


@app.delete("/api/bots/{profile}", dependencies=[Depends(require_token)])
async def delete_bot(profile: str, purge: bool = False) -> dict[str, Any]:
    """Remove a bot: drop it from the roster, then delete its cluster objects.

    The PVC is kept unless `purge` is set, and that default is deliberate — the
    PVC *is* the login. Chrome's profile lives there, so deleting it logs the bot
    out of every account it holds, which is not something a "remove from the
    list" click should do. Keeping it means a bot removed by mistake comes back
    still signed in when it is created again under the same name.
    """
    if not registry.valid_profile(profile):
        raise HTTPException(400, "profile must be lowercase letters, digits and dashes")

    reg = registry.load(settings.registry_path)
    removed = registry.remove(reg, profile)
    if removed is None:
        raise HTTPException(404, f"no bot named {profile}")

    # Drop the roster entry first: if kubectl is unavailable, the bot is still
    # gone from the page, and an orphaned pod is a smaller problem than a card
    # the operator cannot get rid of.
    registry.save(settings.registry_path, reg)

    kinds = ["deployment", "service"] + (["pvc"] if purge else [])
    errors: list[str] = []
    for kind in kinds:
        try:
            done = subprocess.run(
                [settings.kubectl_bin, "-n", settings.namespace, "delete", kind,
                 f"profile-{profile}", "--ignore-not-found"],
                capture_output=True, text=True, timeout=60,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            errors.append(f"{kind}: {exc}")
            continue
        if done.returncode != 0:
            errors.append(f"{kind}: {done.stderr.strip()[:200]}")

    log.info("deleted bot %s (purge=%s)", profile, purge)
    return {
        "ok": not errors,
        "bot": removed.to_dict(),
        "purged": purge,
        # A bot that is off the roster but still has cluster objects is a state
        # worth naming rather than hiding behind ok: true.
        "errors": errors,
    }


@app.get("/", response_class=HTMLResponse)
async def roster_page() -> HTMLResponse:
    ui = Path(__file__).parent / "ui" / "roster.html"
    return HTMLResponse(ui.read_text())


# -- farms -----------------------------------------------------------------
#
# A farm is one task assigned to several bots — the same instruction, run by
# each environment as its own person. The hub owns it because only the hub can
# reach every pod; the routes below are the write side (compose, cancel,
# remove) and the read side the farm room renders, while the firing itself is
# the runner's loop, started in the lifespan above.

_FARM_MODES = ("parallel", "stagger", "schedule")


class CreateFarm(BaseModel):
    name: str = ""
    recipe: str
    task: str
    url: str = ""
    profiles: list[str]
    mode: str = "parallel"
    stagger_seconds: int = 60
    # Only meaningful for mode="schedule": the epoch everyone starts at. A
    # past epoch means "now" — the runner fires on its next tick either way.
    start_at: float | None = None
    # Per-profile clock times on top of start_at — "kai at 10, lex at 11".
    # Unknown profile names are rejected so a typo can't silently fall back.
    start_times: dict[str, float] = {}


def _farm_payload(farm: farms.Farm) -> dict[str, Any]:
    return farm.to_dict()


@app.post("/api/farms", status_code=201, dependencies=[Depends(require_token)])
async def create_farm(req: CreateFarm) -> dict[str, Any]:
    if not req.recipe.strip():
        raise HTTPException(400, "a farm needs a recipe")
    if not req.task.strip():
        raise HTTPException(400, "a farm needs a task")
    if not req.profiles:
        raise HTTPException(400, "a farm needs at least one environment")
    if req.mode not in _FARM_MODES:
        raise HTTPException(400, f"mode must be one of {', '.join(_FARM_MODES)}")
    if req.mode == "stagger" and req.stagger_seconds <= 0:
        raise HTTPException(400, "stagger_seconds must be positive")

    # Catch at assignment time what would otherwise fail identically on every
    # member: a recipe that does not exist, and a recipe with no built-in
    # entry_url (agent.task) that was assigned without a start url.
    from . import recipes  # noqa: F401  (registers the built-ins)
    from .tasks import list_recipes

    known = {r["name"]: r for r in list_recipes()}
    if req.recipe not in known:
        raise HTTPException(400, f"unknown recipe {req.recipe}")
    if not req.url.strip() and not known[req.recipe]["entry_url"]:
        raise HTTPException(400, f"recipe {req.recipe} needs a start url in the payload")

    reg = registry.load(settings.registry_path)
    bots: dict[str, registry.Bot] = {}
    for profile in req.profiles:
        bot = reg.get(profile)
        if bot is None:
            raise HTTPException(400, f"no bot named {profile} on the roster")
        bots[profile] = bot

    unknown_times = set(req.start_times) - set(req.profiles)
    if unknown_times:
        raise HTTPException(400, f"start_times names bots not on the farm: {sorted(unknown_times)}")

    members = farms.build_members(
        list(dict.fromkeys(req.profiles)), bots,
        task=req.task.strip(), mode=req.mode,
        stagger_seconds=req.stagger_seconds, start_at=req.start_at,
        start_times=req.start_times, now=time.time(),
    )
    farm = farm_store.create(
        name=req.name, recipe=req.recipe.strip(), task=req.task.strip(),
        url=req.url, mode=req.mode, stagger_seconds=req.stagger_seconds,
        members=members,
    )
    log.info("created farm %s (%s) -> %d members", farm.id, farm.mode, len(farm.members))
    return {"farm": _farm_payload(farm)}


@app.get("/api/farms", dependencies=[Depends(require_token)])
async def list_farms() -> dict[str, Any]:
    return {"farms": [_farm_payload(f) for f in farm_store.all()]}


@app.get("/api/farms/{farm_id}", dependencies=[Depends(require_token)])
async def get_farm(farm_id: str) -> dict[str, Any]:
    farm = farm_store.get(farm_id)
    if farm is None:
        raise HTTPException(404, f"no farm named {farm_id}")
    return {"farm": _farm_payload(farm)}


@app.post("/api/farms/{farm_id}/cancel", dependencies=[Depends(require_token)])
async def cancel_farm(farm_id: str) -> dict[str, Any]:
    """Cancel what has not started; running members keep running.

    Stopping a live member is a decision made on that bot's own page with its
    own stop button — the farm's cancel is about the assignment, not about
    reaching into pods.
    """
    farm = farm_store.get(farm_id)
    if farm is None:
        raise HTTPException(404, f"no farm named {farm_id}")
    farms.cancel_farm(farm)
    farm_store.persist()
    log.info("cancelled farm %s", farm_id)
    return {"farm": _farm_payload(farm)}


@app.delete("/api/farms/{farm_id}", dependencies=[Depends(require_token)])
async def delete_farm(farm_id: str) -> dict[str, Any]:
    if not farm_store.remove(farm_id):
        raise HTTPException(404, f"no farm named {farm_id}")
    return {"ok": True}


# -- the recipe library ----------------------------------------------------
#
# The hub owns it and is its only writer: the library is shared by every bot, so
# there must be exactly one place an edit lands. A bot pod mounts the same
# directory read-only, which is what makes an edit reach every profile without
# a deploy. Same image, same code — only the mount differs.


def _library() -> recipe_store.RecipeStore:
    return recipe_store.store_for(settings)


def _publish_library() -> tuple[bool, str]:
    """Project the library onto the ConfigMap every bot pod mounts.

    The hub holds the library on its own volume and writes it as plain files —
    one writer, so no races — and this is how that becomes something the pods
    can read. The ConfigMap is a *projection*, not the source of truth, which is
    why it carries no committed data in the manifest: an ``apply`` of that file
    must never be able to reset the operator's recipes.

    ``--from-file`` over the whole directory, so the ConfigMap's keys are exactly
    the files on disk: add a recipe, remove one, and the next publish matches.

    Returns ``(published, reason)``. A failure is *reported*, never raised: the
    operator's edit is already safe in the hub's own copy, and a 500 would say
    the opposite. ``published`` is False whenever the pods cannot yet see the
    change — including when this hub is not configured to publish at all.
    """
    if not settings.recipes_publish:
        # Off by default on purpose: whether this process may write to a cluster
        # is a deployment fact, not something a request should assume.
        return False, "this hub is not configured to publish (RECIPES_PUBLISH)"
    if not _which(settings.kubectl_bin):
        return False, "kubectl is not available; the edit is on the hub but no pod can see it yet"
    directory = settings.recipes_dir
    if not directory.is_dir():
        directory.mkdir(parents=True, exist_ok=True)

    build = [
        settings.kubectl_bin, "-n", settings.namespace, "create", "configmap",
        settings.recipes_configmap, f"--from-file={directory}", "--dry-run=client",
        "-o", "yaml",
    ]
    try:
        rendered = subprocess.run(build, capture_output=True, text=True, timeout=30)
        if rendered.returncode != 0:
            return False, f"could not render the ConfigMap: {rendered.stderr.strip()[:300]}"
        # Applied rather than created: `create` fails once the ConfigMap exists,
        # and applying this rendering replaces the whole data map, which is
        # exactly right — this directory *is* the library.
        applied = subprocess.run(
            [settings.kubectl_bin, "-n", settings.namespace, "apply", "-f", "-"],
            input=rendered.stdout, capture_output=True, text=True, timeout=60,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return False, f"could not publish the library: {exc}"
    if applied.returncode != 0:
        return False, f"could not publish the library: {applied.stderr.strip()[:300]}"
    log.info("published the recipe library to ConfigMap %s", settings.recipes_configmap)
    return True, ""


def _builtin_defaults() -> dict[str, dict[str, Any]]:
    """The value each overridable key falls back to.

    The editor shows this beside every field, because "override" only means
    something against a default. Read off the modules rather than restated, so a
    changed Python literal cannot leave the page describing an old one.

    Best-effort by design: this is display data, and a key that cannot be read
    costs a blank placeholder — never the endpoint.
    """
    from .minesweeper_dom import Pace
    from .recipes import facebook, linkedin, minesweeper, plan_task, x

    pace = Pace()
    out: dict[str, dict[str, Any]] = {}
    for module, recipe in (
        (x, "x.post"),
        (facebook, "facebook.page_post"),
        (linkedin, "linkedin.page_post"),
        (minesweeper, "minesweeper.play"),
        (plan_task, "plan.task"),
    ):
        defaults: dict[str, Any] = {
            "entry_url": getattr(module, "DEFAULT_ENTRY_URL", None),
            "selectors.composer": getattr(module, "DEFAULT_COMPOSER", None),
            "selectors.textbox": getattr(module, "DEFAULT_TEXTBOX", None),
            "selectors.submit": getattr(module, "DEFAULT_SUBMIT", None),
            "max_chars": getattr(module, "DEFAULT_MAX_CHARS", None),
        }
        if recipe == "minesweeper.play":
            defaults["max_clicks"] = getattr(module, "MAX_CLICKS_PER_GAME", None)
            defaults["pace.min_ms"] = pace.min_ms
            defaults["pace.max_ms"] = pace.max_ms
        elif recipe == "plan.task":
            # Its entry_url default is a bare literal in the recipe, not a
            # module constant like the others.
            defaults["entry_url"] = "about:blank"
            defaults["planner_prompt"] = getattr(module, "PROMPT", None)
        out[recipe] = {k: v for k, v in defaults.items() if v is not None}
    return out


@app.get("/api/recipes", dependencies=[Depends(require_token)])
async def list_recipe_config() -> dict[str, Any]:
    """Every built-in recipe with its overrides, plus every stored recipe.

    Merged into one list because that is what the operator sees: a recipe is a
    recipe, and whether it is Python or a saved step list is an implementation
    detail — except where it matters, which is the ``origin`` badge.
    """
    from . import recipes  # noqa: F401  (registers the built-ins)
    from .tasks import list_recipes

    store = _library()
    overrides = store.all_overrides()
    stored = store.specs()
    defaults = _builtin_defaults()

    out = []
    for r in list_recipes():
        name = r["name"]
        out.append({
            "name": name,
            "description": r["description"],
            "entry_url": r["entry_url"],
            "origin": "stored" if name in stored else r["origin"],
            "overridable": list(recipe_store.OVERRIDABLE.get(name, ())),
            "overrides": overrides.get(name, {}),
            "defaults": defaults.get(name, {}),
            "steps": stored.get(name, {}).get("steps") if name in stored else None,
        })
    return {
        "recipes": out,
        "actions": list(recipe_store.STEP_ACTIONS),
        "overridable": recipe_store.OVERRIDABLE,
        "errors": store.errors,
    }


@app.post("/api/recipes/validate", dependencies=[Depends(require_token)])
async def validate_recipe(req: RecipeSpec) -> dict[str, Any]:
    """Dry-run the validator so the editor can refuse before saving.

    No browser involved: this is exactly the check the loader will run, so a
    recipe that validates here is one the pod will accept.
    """
    try:
        spec = recipe_store._validate(req.model_dump(), source="edit")
    except PlanRejected as exc:
        return {"ok": False, "error": str(exc)}
    return {"ok": True, "spec": spec.spec}


@app.post("/api/recipes", dependencies=[Depends(require_token)])
async def create_recipe(req: RecipeSpec) -> dict[str, Any]:
    try:
        spec = recipe_store.save_step_recipe(_library(), req.model_dump())
    except (recipe_store.RecipeError, PlanRejected) as exc:
        raise HTTPException(400, str(exc)) from exc
    return {"ok": True, "recipe": spec, **_published()}


@app.delete("/api/recipes/{name}", dependencies=[Depends(require_token)])
async def remove_recipe(name: str) -> dict[str, Any]:
    """Remove a stored recipe, or clear a built-in's overrides.

    Deliberately one verb for both: "un-edit this recipe" is what the operator
    means either way, and which of the two files changes is not their problem.
    """
    try:
        kind = recipe_store.delete_recipe(_library(), name)
    except recipe_store.RecipeError as exc:
        raise HTTPException(404, str(exc)) from exc
    return {"ok": True, "removed": name, "kind": kind, **_published()}


@app.put("/api/recipes/{name}/config", dependencies=[Depends(require_token)])
async def set_recipe_config(name: str, req: ConfigPatch) -> dict[str, Any]:
    """Merge config overrides for a built-in recipe."""
    try:
        merged = recipe_store.save_overrides(_library(), name, req.values)
    except recipe_store.RecipeError as exc:
        raise HTTPException(400, str(exc)) from exc
    return {"ok": True, "recipe": name, "overrides": merged, **_published()}


def _published() -> dict[str, Any]:
    """Publish the library and report whether the pods can see it yet.

    ``published`` is the honest answer to "did that edit land anywhere a bot can
    read?" — the file is written either way, so a False here is a projection
    problem (publishing not configured, kubectl missing, RBAC short) and not a
    lost edit. It is reported rather than raised: the operator's change is safe
    on the hub, and a 500 would say otherwise.
    """
    published, reason = _publish_library()
    return {"published": published, "publish_error": reason}
